name: hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
      USERNAME: ${{ vars.USERNAME }}
    steps:
      - run: echo "Hello, ${BRANCH}!"
      - uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH}}
      - run: echo "${USERNAME}"