name: hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
      USERNAME: ${{ vars.USERNAME }}
      HASH: ${{ hashFiles('.github/workflows/*.yml') }}
    steps:
      - run: echo "Hello, ${{ env.BRANCH }}!"
      - run: echo "${{ env.USERNAME }}"
      - run: echo "Hash of workflow files ${{ env.HASH }}"