name: manual
on:
    workflow_dispatch:
        inputs:
            greeting:
                type: string
                default: "Hello, World on manual."
                required: true
                description: "The greeting message to display."
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ inputs.greeting }}", "${{github.actor}}"
